### ISSUE TITLE
Jackknife on NK Correlation with Random Subtraction

### ISSUE THREAD

**Issue by zhzhuoqi** [rmjarvis/TreeCorr#102]
Hi Mike, 

It seems that there is a little problem with jackknife on the random subtraction of NKCorrelation. I think treecorr is currently doing separate jackknives on the random and the measured NK, and then add the variances together. But I believe it probably makes more sense to first subtract the random noise and then do a jackknife patch-by-patch. I wrote a brute-force jackknife code comparing the two methods, and their results are in the attached plot. Thanks a lot if you can look into this issue a bit! 

Jackie Zhang

![jackknife](https://user-images.githubusercontent.com/60624040/77696023-aedbf280-6fe7-11ea-9761-6ad7921c1f88.PNG)

**Comment by rmjarvis** [comment]
Yes.  Sorry about that.  This was a bug that I had already fixed for NGCorrelation, but I forgot to apply the same fix to NKCorrelation.  Please try the latest update to the `jk2` branch to see if it matches better now.  Thanks!

**Comment by zhzhuoqi** [comment]
Thanks for updating. I ran another test on CosmoDC2 with the updated version but still got quite different results (see fig) from the brute-force method that I used.
![Capture](https://user-images.githubusercontent.com/60624040/77929470-48531f00-72dc-11ea-96aa-8aa36646e112.PNG)
 I have included a link to my brute-force method on GitHub, so may that may help--the brute-force jackknife is mainly in block 49-54. I expect that the way I did it may somehow underestimate the variance a bit, so I'm also very sure if it is absolutely correct though. Thanks if you can check that!
[https://github.com/zhzhuoqi/bazinga73/blob/master/jackknife_random_subtraction.ipynb]

**Comment by rmjarvis** [comment]
I think this is now fixed and merged into master.  Thanks for doing these tests!  It was super helpful!
