### ISSUE TITLE
HDF5 Support

### ISSUE THREAD

**Issue by joezuntz** [rmjarvis/TreeCorr#105]
Hi Mike,

I'm looking at adding HDF5 support to TreeCorr.Catalog, since that's the native file format for TXPipe and I'd like to use the MPI partial-loading feature to parallelize.

It looks fairly easy and I'm nearly done, as the fitsio interface is not so different from the h5py one.  The only question I have is about the configuration key names.  Sub-sections of HDF files ("groups") are labelled by strings, unlike FITS files whose HDUs can be indexed by integers.   

I think the options are:
- overload (with a slightly wrong name) the `hdu`, `x_hdu`  etc keys, so that they could also be an HDF5 group name as well as a FITS name.  This would involve changing the config system to allow both int and str types for those parameters.
- add an entirely new set of keys, `group`, `x_group`, etc.

Do you have a preference between these? I think the first is more extensible and requires less fiddling.

Cheers,
Joe

**Comment by rmjarvis** [comment]
It seems cleaner to have one set of parameters for both.  Although `hdu` doesn't seem like a great name for this in the HDF5 context.

I suspect `hdu` is not widely used currently, so if I change the name (as a deprecation, so the old name still works for now) it probably wouldn't be too disruptive.  So if we can think of a name that makes sense for both, that would be nice.

The one that jumps to mind is `ext`.  For FITS, `ext` would be which hdu to use.  This is actually already the name that fitsio uses for this.  And for HDF5, `ext` would be which group.  That sounds like it makes sense, right?

Also, just to check, you should rebase your changes onto the current master if you branched more than a few hours ago.  There were some non-trivial changes to this part of the code on the `mpi` branch that I just merged.

**Comment by rmjarvis** [comment]
> This would involve changing the config system to allow both int and str types for those parameters.

This is a feature I've wanted to add for a while anyway, to let FITS extensions be specifiable by name rather than number.  But I haven't gotten around to it.  So 👍

**Comment by rmjarvis** [comment]
Done via #106
