### ISSUE TITLE
patch compatibility with Python 3

### ISSUE THREAD

**Issue by RichardFeder** [rmjarvis/TreeCorr#107]
Hello,

First, thanks for providing access to such a great code base! I am trying to compute the 2PCF for an intensity field (and its sample variance) using the KKCorrelation module, but when I try to define npatch while instantiating the Catalog object, I get an error (traceback below). I tried with the Python 2 version of the code and it seems like the patches do work there. I downloaded the Python 3 version using "pip3 install treecorr". Any help on this would be greatly appreciated!

![Screen Shot 2020-05-18 at 7 27 55 PM](https://user-images.githubusercontent.com/8354963/82277840-b9f33500-993d-11ea-8c70-99823f1cbc14.png)

**Comment by rmjarvis** [comment]
I don't know exactly what went wrong on your installation, but that's not version 4.1.1.

You can see for instance that line 390 in catalog.py is something completely different:
https://github.com/rmjarvis/TreeCorr/blob/v4.1.1/treecorr/catalog.py#L390

I'd try uninstalling (possibly repeatedly) with `pip uninstall treecorr`.
And then install again.

**Comment by RichardFeder** [comment]
Yeah, it seems to have been a slightly earlier version. Uninstalling and reinstalling twice worked! Thanks for your help.

**Comment by rmjarvis** [comment]
Great!  Glad it was that simple to fix.  :)
