### ISSUE TITLE
Calculating Covariance Matrix after using process_cross

### ISSUE THREAD

**Issue by Federico-Berlfein** [rmjarvis/TreeCorr#109]
Hi Mike,

I have been using TreeCorr for a few years now and love the new addition of covariance matrices! However, I did run into a problem when trying to use the estimate_cov() method after using process_cross(), and then finalize() functions, rather than using process() directly. For example, the estimate_cov() function works correctly when doing something like this:

`nk = treecorr.NKCorrelation(min_sep= 10, max_sep=1000 , nbins=100)`
`source_cat = treecorr.Catalog(ra = ra_source, dec=dec_source, r = r_source, ra_units='deg', 
dec_units='deg', patch_centers = patch_cent)`
`lens_cat = treecorr.Catalog(ra = ra_lens, dec= dec_lens, r = r_lens, k= k_lens , ra_units='deg', 
dec_units='deg', patch_centers = patch_cent)`
`nk.process(source_cat, lens_cat)`
 `cov_jk = nk.estimate_cov('jackknife')`

but throws a `Using jackknife covariance requires using patches.` when using process_cross and finalize:

`nk = treecorr.NKCorrelation(min_sep= 10, max_sep=1000 , nbins=100)`
`source_cat = treecorr.Catalog(ra = ra_source, dec=dec_source, r = r_source, ra_units='deg', dec_units='deg', patch_centers = patch_cent)`
`lens_cat = treecorr.Catalog(ra = ra_lens, dec= dec_lens, r = r_lens, k= k_lens , ra_units='deg', dec_units='deg', patch_centers = patch_cent)`
`nk.process_cross(source_cat, lens_cat)`
`vark = treecorr.calculateVarK(lens_cat)`
`nk.finalize(vark)`
`cov_jk = nk.estimate_cov('jackknife')`

It seems to me that the patches are not being preserved after using process_cross. Please let me know what you think of this!

Thanks for your help!
Federico Berlfein

**Comment by rmjarvis** [comment]
You're correct about that.  The patch calculations are only done for the regular `process` call.  Indeed, that job calls `process_cross` behind the scenes for each pair of patches and keeps track of all the pairwise results.

Is there some use case where you need to be doing this with an explicit `process_cross` call rather than just `process(source_cat, lens_cat)`?

**Comment by Federico-Berlfein** [comment]
Thanks for the quick response Mike. Yes, I use `process_cross` because I am cross correlating multiple catalogs, rather than just one, so I need to use this function in order to accumulate the counts in each bin appropriately from each cross correlation.

If patch calculations are not supported by`process_cross`, the only solution I can think of is calculating each catalog individually using `process`, on top of using `process_cross` on a different `Correlation` object, and use `treecorr.estimate_multi_cov` for all of the `Correlation` instances that used `process`. However, this seems time-costly, as the cross-correlation has to essentially be done twice, one for the measurement and one for error. Let me know if you have a different perspective on how to do this.
Thanks!

**Comment by rmjarvis** [comment]
What is the nature of the multiple catalogs?  Are they all complete over the same region of the sky, but represent different kinds of lenses or something?

Or are they logically all one catalog that just happens to be broken up into different files for size reasons or something like that?

I think maybe the API that could make sense (for either of these situations actually) would be for `process` to have a `finalize=False` option that would skip the finalization step to allow process to be called multiple times, accumulating the patch information properly from multiple pairs of catalogs.  Then either the last time you would set finalize=True, or you could handle it yourself if you wanted.

Does that sound like it would work?

**Comment by Federico-Berlfein** [comment]
Yes the nature of multiple catalogs is representing different lenses over the same region of the sky. 

I think the solution you propose would work, it would essentially make `process(finalize = False)` the patch-friendly version of `process_cross` if I understood correctly. And once all the catalogs are processed this way, the `finalize` method can be called similarly to the way it is done when using `process_cross`, or with `finalize=True` on the last one like you proposed. Sounds good to me!

**Comment by rmjarvis** [comment]
For now, I suspect you can get what you need by combining the lens catalogs by hand into a single larger catalog
```
all_lens = Catalog(ra=np.concatenate([lens1.ra, lens2.ra]),
                   dec=np.concatenate([lens1.dec, lens2.dec]),
                   ...)
```
Then use that for the complete lens catalog.

**Comment by Federico-Berlfein** [comment]
Sounds good, thanks for the help!

**Comment by rmjarvis** [comment]
Done in #120.
