### ISSUE TITLE
conda install

### ISSUE THREAD

**Issue by AstroMike** [rmjarvis/TreeCorr#113]
To install from conda the command is now

` conda install -c conda-forge treecorr `

from  https://anaconda.org/conda-forge/treecorr

worked for me!

**Comment by rmjarvis** [comment]
Sorry, you're right.  That's an oversight in the README.  I have conda-forge in my default conda chnnel list, so I don't have to specify it.  But you're quite right that the official docs should mention it explicitly.  I will fix this.
