### ISSUE TITLE
Avoiding repeated writing of identical patches with save_patch_dir

### ISSUE THREAD

**Issue by enourbakhsh** [rmjarvis/TreeCorr#116]
The `save_patch_dir` option tries to make new patches even if they already exist. This happens when they're already made in a previous run or are made/being made by another parallel process in the current run. For example, in the calculation of `S1xS2` and `S1xS1` shear-shear correlations (`S1` and `S2` stand for the first and second tomographic bins in the source catalog), if `S1` patches are already made through `S1xS2` then they shouldn't be recomputed and saved again for `S1xS1`. I'm wondering if there are ways to avoid this unnecessary I/O by changing it to check if the file exists and not rewrite it if it's already there or being created by another parallel process. We also need to consider the race condition.

**Comment by rmjarvis** [comment]
Done in #119.
