### ISSUE TITLE
Bug when using patches and the Rlens metric

### ISSUE THREAD

**Issue by marina-ricci** [rmjarvis/TreeCorr#131]
I found a bug preventing from using patches when using the Rlens metric. 
When computing cross-correlation (NN or NK) between one catalog with (ra, dec, r) and the other with (ra,dec) I obtain the following error : `ValueError: Invalid coords None`. No error when using only one patch or no patch.

**Comment by rmjarvis** [comment]
Fixed on #130.  Thanks for the bug report Marina!

**Comment by rmjarvis** [comment]
The fix for this was released (a while ago now...) in version 4.2.4.
