### ISSUE TITLE
Access correlation function for jackknife

### ISSUE THREAD

**Issue by Uendert** [rmjarvis/TreeCorr#132]
Hello Jarvis,

Is there a simple way to access the correlation function that would have been measured if one patch at a time is excluded from the sample, as is done internally for the jackknife? In other words, I'd like to have access to the sample of \xi_i computed when excluding one patch at a time. Maybe this can be an attribute similar to the covariance matrix. 

Thanks for your time,
Uendert

**Comment by rmjarvis** [comment]
Hi Uendert, I finally got around to implementing this.  Now there are functions `corr.build_cov_design_matrix` and `treecorr.build_multi_cov_design_matrix` (corresponding to `corr.estimate_cov` and `treecorr.estimate_multi_cov` respectively).  

If you'd like to take a look, the PR is #146.  Let me know if this doesn't seem to have what you need.  It's slated to be released with the next minor version, 4.3.
