### ISSUE TITLE
Problem with NN_correlation when setting low_mem=True

### ISSUE THREAD

**Issue by chto** [rmjarvis/TreeCorr#144]
Hi, 

I find that the result of NN_correlation when setting `low_mem=True` depends on whether the catalog is saved in the unit of `radian` or `degrees`. Specifically,  I find that when saving the catalog in the unit of radian, the npairs of NN_correlation result does not depend on whether low_mem is set to True or False. 
![download (20)](https://user-images.githubusercontent.com/16754618/172995077-39bd99b1-16a0-41e0-bb31-a7fe243baf98.png) 

But, if the catalog is saved in the unit of degree,  NN_correlation result depends on low_mem. 
![download (21)](https://user-images.githubusercontent.com/16754618/172995131-a156dbea-fc29-4f76-8ffe-37894114c97b.png)

Here is a simple colab example to demonstrate this, 
https://colab.research.google.com/drive/1CnFyKpjQVK7Vw64r5u-sj6c3rRIQVAcH?usp=sharing 
The treecorr version used is 4.2.8. 

Upon further investigation, I believe the problem is at this line,  https://github.com/rmjarvis/TreeCorr/blob/234b90ed4b02350e4e0064d890f2a8b3cbd2edf5/treecorr/catalog.py#L2012 
I think it assumes that all the saved patch files are in the unit of radian. 
 

![download (21)](https://user-images.githubusercontent.com/16754618/172995083-4c88781a-e021-4492-9365-af0f33e11840.png)

**Comment by rmjarvis** [comment]
Thanks Chun-Hao.  I've fixed this in #145.  Thanks so much for reported the error!
