### ISSUE TITLE
Computing "scaled counts-in-spheres"

### ISSUE THREAD

**Issue by felipeavila331** [rmjarvis/TreeCorr#148]
I have been using the TreeCorr code for a few years. At the moment I need to do a count in spheres for a radius r, for both the galaxy catalog and the random ones, and get the ratio between the two, N_cat(r) / N_rand(r). Is this possible with TreeCorr?

This ratio, in general, can be obtained from the volumetric integral of the correlation function. However, this integral seems to be very sensitive to binning and minimum separation in the correlation function. So I would like to calculate this ratio directly from the data.

**Comment by rmjarvis** [comment]
Is this what you want? 
https://rmjarvis.github.io/TreeCorr/_build/html/field.html#treecorr.Field.get_near

**Comment by rmjarvis** [comment]
Also, https://rmjarvis.github.io/TreeCorr/_build/html/field.html#treecorr.Field.count_near, which just counts points.

**Comment by felipeavila331** [comment]
Yes, I think that solves my problem, thank you.

**Comment by rmjarvis** [comment]
OK.  Closing this issue, but please feel free to reopen if that turns out not quite to do what you need or if you have problems using them.
