### ISSUE TITLE
TwoD Binning in Rperp metric.

### ISSUE THREAD

**Issue by rpaviot** [rmjarvis/TreeCorr#149]
Hi,

I have implemented a code that compute projected clustering (NG correlation for intrinsic alignments wg+(rp), NN correlation for wgg(rp)), with the Rperp metric.  Since TwoD binning is only valid in Euclidean metric, with linear binning along rp and pi, i cannot use this metric to compute the projected quantities that i want.

Instead, if i want wg+ for example, i have to loop over radial distances, for example between pi = -100 to + 100 Mpc/h specifing each time to the NG correlations a new min_rpar, and max_rpar, but this is really time consuming.

 Would it feasible to implement TwoD in the Rperp metric with a log binning in rp?
 Thanks,
Romain

**Comment by rmjarvis** [comment]
Can you give evidence that it is "really time consuming"?  What you described is the standard way to do it, and I don't think there is much efficiency to be gained by letting TreeCorr do it internally.

**Comment by rmjarvis** [comment]
Closing due to lack of response.  I don't think there is any advantage to having TreeCorr do the requisite loop over pi values rather than letting the user do so.
