### ISSUE TITLE
is bin_slop in log or linear space when using log binning?

### ISSUE THREAD

**Issue by beckermr** [rmjarvis/TreeCorr#163]
As in the title.

**Comment by rmjarvis** [comment]
cf. https://rmjarvis.github.io/TreeCorr/_build/html/binning.html#bin-slop

The units of bin_slop is bins.

**Comment by beckermr** [comment]
I read the docs and am still confused. I see

> The approximation TreeCorr makes is to allow some additional imprecision that is a fraction of this level. Namely bin_slop. Specifically, bin_slop specifies the maximum possible error any pair can have, given as a fraction of the bin size.

For log binning, is the bin size `log(10) - log(20)` or `10-20`?

**Comment by rmjarvis** [comment]
The log values are what are relevant if doing log binning.

In the interest of extreme precision, here is the code that does the calculatios:
https://github.com/rmjarvis/TreeCorr/blob/releases/4.3/include/BinType.h#L111
