### ISSUE TITLE
inconsistency between TreeCorr and Athena when using simulation

### ISSUE THREAD

**Issue by YaoQianli** [rmjarvis/TreeCorr#175]
Hi! I recently found a very confusing situation when using TreeCorr. I can almost perfectly recover KiDS results when calculating the shear-shear correlation with KiDS data (2007.15633). But when I use the same code on a simulation (without intrinsic ellipticities), TreeCorr gives overestimated xi+ and almost null xi-. When I switch to Athena, it provides what I expect. The comparisons are shown in the figure.

![image](https://github.com/user-attachments/assets/0592d9da-fb81-43dc-b722-7f4fe26295e3)

Do you have any clue what is going on? Is there anything particular I need to take care of when applying TreeCorr to simulations?

**Comment by rmjarvis** [comment]
Many simulations define ellipticities from the perspective of the light bundle heading towards earth, rather than telescopes looking up into the sky at the galaxy.  The result is they have g2 with the opposite sign.  Try using flip_g2=True and see if that gives you something more sensible.

**Comment by YaoQianli** [comment]
It is solved! You are right it is caused by the flip of g2.
![image](https://github.com/user-attachments/assets/5240d2df-d7f9-4115-8b5d-f4c71214ce77)

Thanks a lot!
