### ISSUE TITLE
mean(radius) for correlation function bins

### ISSUE THREAD

**Issue by NiallMac** [rmjarvis/TreeCorr#28]
For 2pt correlations, the separation value currently returned is meanlogr, i.e. the mean of the log separation of the pairs in the bin. It would be useful to have the actual (weighted) mean separation, since I believe this is the separation at which you want to compute the theoretical signal you're comparing to. For wide bins the difference can be significant.

**Comment by rmjarvis** [comment]
Sure.  I can certainly add that.  

Although, it isn't obvious to me which measure is the more appropriate one for the theory value.  I actually would have expected that if the signal is locally approximately a power law, then the mean(log(r)) would be more accurate.  But I suppose this could be tested with some simulations.

In any case, it shouldn't be hard to add mean(r) in addition to what is currently calculated.

**Comment by NiallMac** [comment]
Ah right, yes, for a power law mean(log(r)) is correct. So I think we can forget this! I will do some tests to make sure mean(log(r)) is accurate enough for my purposes. But I see now that it is the appropriate single separation value to return. Cheers.

**Comment by rmjarvis** [comment]
@NiallMac I went ahead and implemented this feature.  It's in the current master branch version and will be included in version 3.2.  Now it accumulates both meanlogr and meanr.  So users can decide which version is more appropriate for their use case.  Of course with small enough binning, there is no appreciable difference between meanr and exp(meanlogr), but for wider binning, the difference might be significant enough to care about.

**Comment by NiallMac** [comment]
Thanks Mike
