### ISSUE TITLE
weights in NN correlations

### ISSUE THREAD

**Issue by suchyta1** [rmjarvis/TreeCorr#29]
Is the weight column okay to use with NN correlations? I’m setting a bunch of the weights to zero, and one thing I’ve noticed, is I get very different results if I remove all the zero weights. Maybe the weights are being ignored?

**Comment by rmjarvis** [comment]
Yes.  The weights are being ignored for NN.  Sorry about that. 

Should be a pretty easy fix.  I'll be addressing a number of TreeCorr issues later this summer (after the SV papers are submitted).  So I'll fix this then.

**Comment by rmjarvis** [comment]
Done on master.  Will be in version 3.2.
