### ISSUE TITLE
3d correlation question

### ISSUE THREAD

**Issue by reikonakajima** [rmjarvis/TreeCorr#30]
Hi Mike,
I've used your TreeCorr code to do some 3D 2pt correlation calculation, and the results are coming out strange:
![pk_g09](https://cloud.githubusercontent.com/assets/1471646/8694980/c59503bc-2ae2-11e5-8059-e2983d405150.png)
You can see that the sharp structure is showing up on the 1 deg^2 patches (the thin colored lines), as well as in the overall correlation function (heavy blue dots).  Would you have any suggestions as to what I'm doing wrong?  I've been using your 2D 2pt correlation calculation, and the output for those makes sense.

I'm using the following Python commands:
```
data_cat = treecorr.Catalog(ra=ra, ra_units='deg', dec=dec, dec_units='deg', r=r_comoving)
rand_cat = treecorr.Catalog(ra=rand_ra, dec=rand_dec, ra_units='deg', dec_units='deg', r=rand_r_comoving)
dd = treecorr.NNCorrelation(nn_3d_config_single)
```
where `nn_3d_config_single` is a file that specifies `min_sep`, `max_sep`, and `nbins`.  I did not specify `sep_units`, since I assumed it just uses the units for `r`, as-is.

The TreeCorr version is v3.0.2.

**Comment by reikonakajima** [comment]
Hi Mike,

I've tried running another 3d correlation code (mine), and it's showing the same kink structure.  So it appears that the data is problematic, not the treecorr code.  I'll close this issue.

**Comment by rmjarvis** [comment]
OK.  Thanks for the update, Reiko.  I wasn't sure how to investigate this, so I'm glad it wasn't a problem with TreeCorr.
