### ISSUE TITLE
feature request: enable the use of two sets of weights in computations

### ISSUE THREAD

**Issue by beckermr** [rmjarvis/TreeCorr#31]
This request is for the ability to use two sets of weights in the computations. The first set would b eused to do all tree building, traversal and pairings of cells. The second set would be used just to accumulate the quantities in each cell that contribute to the 2pt function.

**Comment by rmjarvis** [comment]
I'm not sure if this description is quite the best way to think about this.  Here is how I'm thinking about it:

One set of weights would be used for all calculations involving positions.  Specifically the weighted centroid of every cell: xc = Sum(w x)/Sum(w), yc = Sum(w y)/Sum(w).

Another set of weights would be used for the products used for the correlations: Sum(wa wb ea eb) / Sum(wa wb).

So different weights for the two kinds of quantities that get weighted.  I think this is essentially what you are asking for.

**Comment by beckermr** [comment]
Sounds great.

**Comment by rmjarvis** [comment]
Done on master.  Will be in version 3.2.

**Comment by beckermr** [comment]
Thanks!
