### ISSUE TITLE
feature request: Max/min line of sight separation for summing pairs in new rperp metric

### ISSUE THREAD

**Issue by matroxel** [rmjarvis/TreeCorr#34]
Adding an option to restrict the line of sight separation of pairs summed using the new rperp metric. For (rp, Pi) coordinates, this amounts to an integration limit in the Pi direction. In practice, it just excludes pairs where Delta Pi > los_max. Useful in both limits, a maximum los separation (for IA) and minimum line of sight separation (for gg lensing).

**Comment by rmjarvis** [comment]
Done on master.  Rlens and Rperp metrics are allowed to give min_rpar, max_rpar parameters which limit the minimum and maximum value of r_source - r_lens, where "source" is the second catalog of the two, and "lens" is the first catalog.  

This is a signed quantity, so to specify that you only want background galaxies, you can use `min_rpar = 0`.  To specify that you only want local galaxies (for II or halo studies) you can use e.g. `min_rpar = -50` and `max_rpar = 50`.

One caveat is that I don't use the min/max rpar values for splitting, just for pruning pairs of cells.  This means that if you want a fairly exact rpar cutoff, you might need to use a lower than normal bin_slop to make sure that the regular splitting process gets down to small enough cells that the error in rpar is small.  OTOH, I suspect most people won't need the rpar cutoff to be extremely precise, so I think this is fine.

The usual recommendation about bin_slop applies: Check if using a bin_slop half as large makes any significant difference to the statistic you are making, and if not, then you're fine.  If it makes a difference, you probably need to go smaller.
