### ISSUE TITLE
feature request: g1, g2 in addition to gtan, gcross

### ISSUE THREAD

**Issue by msimet** [rmjarvis/TreeCorr#38]
We had a request for this as part of Stile: one of our users looks at <g1g1> and <g2g2> as diagnostics of possible chip-frame shape measurement problems.  I wasn't sure if this was something easy to add to TreeCorr, or if you had any plans to do something with it, so I thought I'd ask!

**Comment by rmjarvis** [comment]
If you don't want to let g rotate physically relative to the line joining the two objects, then it's really just a scalar, not a spinor.  Or two scalars, really.  So just do KK or NK correlations using g1 and g2 as the scalar "K" values. e.g. 
```
g1cat = galsim.Catalog(k=g1, ...)
corrg1 = NKCorrelation(...)
corrg1.process(ncat, g1cat)
meang1 = corrg1.xi
```
This will give the mean g1 vs distance from the points in `ncat`.  Likewise for the g2 component.

Did I properly understand what you want here?  Is this an acceptable solution?

**Comment by msimet** [comment]
Ah, yes, that would work!  Thanks.
