### ISSUE TITLE
Feature request: get indices of nearby points

### ISSUE THREAD

**Issue by ebaxter** [rmjarvis/TreeCorr#44]
Say we create a tree, TREE, from two arrays, RA and DEC.  I think it would be useful to have a method "query_point" that returns the indices of points in the RA and DEC arrays that are within a given distance from the queried point.  So, for instance, one could do:

```
RA0 = 90.
DEC0 = 0.
radius = 10.
indices = TREE.query_point(RA0, DEC0, radius)
RA_nearby, DEC_nearby = RA[indices], DEC[indices]
```

This is exactly analogous to the "query_ball_point" method in scipy.spatial.KDTree: http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.KDTree.query_ball_point.html#scipy.spatial.KDTree.query_ball_point.  

Thanks!

**Comment by rmjarvis** [comment]
Done on #82.

@ebaxter if you want to check it out, the typical syntax would be as follows:
```
# corr is any of the various ??Correlation types
corr.process(cat, cat2)
field = cat.field
indices = field.get_near(RA * coord.degrees, DEC * coord.degrees, sep=1.5 * coord.arcmin)
ra_nearby = cat.ra[indices]
dec_nearby = cat2dec[indices]
```
There are a number of allowed ways to specify the position for the `get_near` function.  cf. [its doc string](https://github.com/rmjarvis/TreeCorr/pull/82/files#diff-e33ec580260836945c05cb465bf463f5R150).

Also, if you haven't called process for a catalog, then you can make a field manually with
```
field = cat.getNField()
indices = field.get_near(...)
```
I think this does what you want, but please do try it out and make sure it works for you.
