### ISSUE TITLE
Installation hangs

### ISSUE THREAD

**Issue by tmcclintock** [rmjarvis/TreeCorr#45]
I attempted to install treecorr on a new anaconda installation that I have been using, and the treecorr installation hung at the line:
Running setup.py bdist_wheel for TreeCorr ... \

The installation was hung here for about a day.

**Comment by rmjarvis** [comment]
Thanks for letting me know.  This is apparently an [issue](https://github.com/pypa/pip/issues/2732) with interactive setup.py files.  Recent versions of pip now suppresses all output from setup.py, so there is no way to tell that it might be waiting for a response from you.  Kind of annoying, but they seem to think this is a feature, not a bug, so I guess it's on me to change setup.py to deal with this.

Here is the message that is apparently being suppressed:
```
WARNING: TreeCorr uses cffi, which in turn requires libffi to be installed.
         As the latter is not a python package, pip cannot download and
         install it.  However, it is fairly straightforward to install.

On Linux, you can use one of the following:

    apt-get install libffi-dev
    yum install libffi-devel

On a Mac, it should be available after you do:

    xcode-select --install

If neither of those work for you, you can install it yourself with the
following commands:

    wget ftp://sourceware.org:/pub/libffi/libffi-3.2.1.tar.gz
    tar xfz libffi-3.2.1.tar.gz
    cd libffi-3.2.1
    ./configure --prefix={prefix}
    make
    make install
    cp */include/ffi*.h {prefix}/include
    cd ..

If you have already done this, then check the command (given above) that failed.  You may
need to add a directory to either C_INCLUDE_PATH, LIBRARY_PATH, or LD_LIBRARY_PATH to
make it succeed.

Stop the installation here to take care of this? [Y/n] 
```
(Of course, it will format this so {prefix} is the right thing given where you are trying to install TreeCorr.)

Clearly, I should have this query time-out after some reasonable length of time, so it doesn't hang.  And I'll look to see if there is a way to tell that it is being run by pip, so the user can't even see the question, in which case I can just have it fail immediately.  Although I'm not sure how to get the message about why it's failing past the pip firewall.  I'll need to investigate that.

In any case, the immediate solution for you is probably to just make sure libffi is installed (as described above) and try again.  You could also try installing from source where you will see the output of what setup.py is trying to do in case there are any other issues.

**Comment by tmcclintock** [comment]
Ahh thanks for letting me know. When I did the manual install I received that error message and thought to myself "Huh this looks complicated, but I guess since the pip installation handles this by itself I'll just wait for Mike to fix that issue".

I guess I thought wrong :).

**Comment by rmjarvis** [comment]
I updated the prompt to time out after 30 seconds.  It's hard for me to test that this will give a reasonable error message if this happens via pip (since pip suppresses the relevant output from setup.py, and all my systems now do have libffi installed), but at least it shouldn't hang anymore.  

If you come across a system where this fix doesn't seem to be sufficient, please reopen this issue and let me know what the output looks like.
