### ISSUE TITLE
Backward compatability lost with config files

### ISSUE THREAD

**Issue by tmcclintock** [rmjarvis/TreeCorr#47]
Disclaimer: I do not know which version of TC broke this compatability, I only know that it was broken.

Previously I used configuration files without an extension (e.g. config_file) that contained lines that looked like the following:

file_name = foobar.txt

I went to run some of my old scripts again and TC failed saying that it couldn't recognize the configuration file from the extension. I have moved over to using .yaml files based on the sample configuration file in the repo, but I wanted to raise an issue that backward compatibility was lost with one of the recent updates. This was using TC version 3.3.3.

**Comment by rmjarvis** [comment]
Yes, as reported here: http://rmjarvis.github.io/TreeCorr/html/changes.html#api-changes

The old behavior is preserved if your config file is names *something*.params.  Or if you run `corr2 -f params config_file`.
