### ISSUE TITLE
Feature request: Marked point bootstrap error estimator

### ISSUE THREAD

**Issue by mdschneider** [rmjarvis/TreeCorr#50]
This [Loh (2008) paper](https://arxiv.org/abs/0805.2325) describes an algorithm to estimate bootstrap errors on spatial correlation function estimators that is both faster and more accurate than bootstrap estimators that resample spatial blocks of the data (i.e., in sky regions that are subsets of the survey footprint).

To implement the marked point bootstrap, we need to be able to resample the pair counts in annuli around each galaxy or star (these are the 'marks' for the algorithm). From a cursory inspection of the code, it is not clear if such marks are easily accessible given the way the pair counts are computed.

Still, I think this error estimator would be valuable as an alternative to jackknife.

**Comment by rmjarvis** [comment]
This is done in PR #96.

**Comment by rmjarvis** [comment]
Will be included in v4.1.0
