### ISSUE TITLE
config File read in as string

### ISSUE THREAD

**Issue by ltlancas** [rmjarvis/TreeCorr#52]
Hi, when I try to follow the instructions in the guide to using the Python module of Treecorr I seem to get a few errors. Specifically, when I have 

`import treecorr
config = treecorr.read_config("config.yaml")
treecorr.corr2(config)`

I get an Attribute Error saying 

`AttributeError: 'str' object has no attribute 'get'`

It seems that Python sees 'config' as a string and I'm not sure what it should be seeing it as.  Is there something obvious that I'm missing here? Thanks for any help.

**Comment by ltlancas** [comment]
The issue was that my config.yaml file had assignments using '=' rather than ':' it would be nice if it were specified anywhere in the tutorial that this should be the case.

**Comment by rmjarvis** [comment]
This is the normal YAML syntax.  The [tutorial](https://github.com/rmjarvis/TreeCorr/blob/releases/3.3/tests/Tutorial.ipynb) does show what the example config file looks like in In[3], which shows the colons.  There is also a [sample_config.yaml](https://github.com/rmjarvis/TreeCorr/blob/releases/3.3/sample_config.yaml) that also shows an example of the correct syntax for YAML config files.  I'm sorry that you didn't notice these, but I'm not sure what else to add to the tutorial to call out the YAML syntax.

However, I admit that the error message you got was not particularly informative, so I'll look into having it give a more useful message for ill-formed configuration files.

**Comment by ltlancas** [comment]
Thanks for the feedback! You're right, I did not notice those and feel silly now.  What threw me off was how in the configuration parameters page (https://github.com/rmjarvis/TreeCorr/wiki/Configuration-Parameters) there are "=" in front of all the parameter names, so this is what I thought had to be in the yaml file.

**Comment by rmjarvis** [comment]
Ah, good point.  I'll change that page to use colons.
