### ISSUE TITLE
Slight update required in the installation instructions for libffi

### ISSUE THREAD

**Issue by tmcclintock** [rmjarvis/TreeCorr#54]
In the github page under installation step 1 part d it instructs us to update C_INCLUDE_PATH and LIBRARY_PATY, but when actually doing the installation we will recieve instructions to also update LD_LIBRARY_PATH.

Either updating LD_LIBRARY_PATH should be added to the instructions on the github page or removed from the message when doing the installation, so that they are consistent.

**Comment by rmjarvis** [comment]
I think it never hurts to set both.  But I'm not actually sure if LD_LIBRARY_PATH is required in this case.
You said you had trouble on nersc.  Did you need the LD_LIBARARY_PATH on that system?

**Comment by tmcclintock** [comment]
No my issue was that I was being stupid and I had the paths wrong, so I figured that out. I don't know if LD_LIBRARY_PATH is required either, since I just updated all three paths.

**Comment by rmjarvis** [comment]
OK.  Regardless, I'll update the README to mention LD_LIBRARY_PATH in addition to LIBRARY_PATH.
