### ISSUE TITLE
Correlations on a periodic grid

### ISSUE THREAD

**Issue by rmjarvis** [rmjarvis/TreeCorr#56]
I was chatting with @aphearin last week, and he was interested in potentially running TreeCorr on a field with periodic boundary conditions.  This kind of data is generated by simulations.  I think this would not be too hard to implement as a different Metric now that I have this concept in TreeCorr.

The Catalog should have optional `x_period`, `y_period`, `z_period` parameters to specify the length of the period in each dimension.

Then `nn.process(cat, metric='Periodic')` would essentially calculate `fmod(x1-x2, x_period)` (and likewise in the other dimensions) when calculating the distance between two points.

**Comment by aphearin** [comment]
Yes, @rmjarvis - I think many theorists working with simulations would find this feature very useful. In case you'd like to run benchmarks and/or unit-tests against external code, the [Halotools](http://halotools.readthedocs.io) implementation of this feature is called [npairs_3d](http://halotools.readthedocs.io/en/latest/api/halotools.mock_observables.npairs_3d.html#halotools.mock_observables.npairs_3d).

**Comment by rmjarvis** [comment]
Great.  Thanks Andrew.

**Comment by rmjarvis** [comment]
Done on #84.
