### ISSUE TITLE
Errors on NN correlation

### ISSUE THREAD

**Issue by ltlancas** [rmjarvis/TreeCorr#62]
Hi,

  I'm just wondering how the errors on the two-point correlation are calculated in the code and couldn't find exactly how it was done by looking on the website. Let me know if there's an easy reference!

Thanks!

**Comment by rmjarvis** [comment]
I assume by "errors", you mean the estimates of the uncertainty, `varxi`.  It's just a straightforward [propagation of Poisson errors in the counts](https://github.com/rmjarvis/TreeCorr/blob/releases/3.3/treecorr/nncorrelation.py#L380).

The code doesn't currently make any attempt to estimate sample variance, so these are always underestimates of the true uncertainty.  To include sample variance, you should generally do some kind of [bootstrap](https://github.com/rmjarvis/TreeCorr/issues/50) or [jackknife](https://github.com/rmjarvis/TreeCorr/issues/24) style covariance estimate, but these are not integrated into TreeCorr yet, so you'd have to do them yourself.  (Or many people use theory covariances.)

**Comment by ltlancas** [comment]
Yup yup, that's what I meant. Okay, this is what I suspected but thanks for the clarification!
