### ISSUE TITLE
Use of w_col

### ISSUE THREAD

**Issue by DriftingPig** [rmjarvis/TreeCorr#63]
Hello,
I guess the w_col is for weighing each data. However, when I use this column, I got the same result with when I didn't use this column. My data has w=1 for data files, and w varies for random files. I am using the 3D correlation function, NNcorraltion. 
Will the pairs multiply the weights, like w1*w2 for each pair , or the weights have other meanings?
Cheers,
Hui

**Comment by rmjarvis** [comment]
If you're using weights, you want to look at the nn.weight attribute, not nn.npairs.  This should be the sum of w1*w2 for each pair as you expected.  If it's not working for you, please submit a self-contained example that isn't doing what you expect, and I can take a look.
