### ISSUE TITLE
Finding cffi library using pkgconfig

### ISSUE THREAD

**Issue by EiffL** [rmjarvis/TreeCorr#68]
On my system (ArchLinux) cffi is properly installed (in /usr/lib and /usr/lib/libffi-3.2.1/include), but the setup.py fails to see it. I can hack around it, but it would be better to add a pkgconfig check before failing. Feel free to assign this to me :-)

**Comment by rmjarvis** [comment]
Definitely, if you can come up with some addition to setup.py that will find this properly for your system, please do submit a PR for it.  I thought it would have been able to find something in /usr/lib, but this might rely on some system setups that might not apply to your system.  So if pkg-config can tell you some flags to add, that sounds like a good thing to add (probably only if the existing check fails I guess).

**Comment by rmjarvis** [comment]
François, do you know if this is still an issue?

I was looking at setup.py, and it only tries to compile anything related to libffi if `import cffi` raises an ImportError.  It's just trying to give a heads up that when it gets to installing cffi for you that there might be an issue.

If you actually have cffi installed properly (as you said), then I don't think TreeCorr's setup.py should be running into any problems.  It just imports cffi and moves on.

So is the problem just that my messaging is incorrect?  Like TreeCorr says it will have trouble installing cffi, but you didn't actually have any problem doing `pip install cffi`?  Or was cffi properly installed, and `import cffi` works from your python, but somehow setup.py got an `ImportError` when it tried to do it?

Just trying to understand what, if any, action I should take with respect to this issue.

**Comment by rmjarvis** [comment]
Closing due to lack of response.
