### ISSUE TITLE
varxi missing factor of 2 for xi+/-

### ISSUE THREAD

**Issue by NiallMac** [rmjarvis/TreeCorr#72]
I mentioned this to @rmjarvis a while back but I think I never actually started an issue. I believe the way treecorr calculates varxi for xi+/- is missing a factor of 2. I think this is most clear by considering xi+/- = C_tt +/- C_xx where C_tt is the correlation function of the tangential shear components and C_xx is the correlation function of the cross components. The expression in this line https://github.com/rmjarvis/TreeCorr/blob/releases/3.3/treecorr/ggcorrelation.py#L252 would be appropriate for C_tt or C_xx, so the variance of xi_+/- should be twice that. In case useful, I've attached some notes with a derivation of the shape noise variance for xi+/-. 
[shape_noise_xipm.pdf](https://github.com/rmjarvis/TreeCorr/files/2548959/shape_noise_xipm.pdf)

**Comment by rmjarvis** [comment]
Thanks Niall.  I agree.  This will help me remember to fix this before the next release.

**Comment by rmjarvis** [comment]
Done in PR #79
