### ISSUE TITLE
Change definition of Rperp to use Fisher et al definition

### ISSUE THREAD

**Issue by rmjarvis** [rmjarvis/TreeCorr#74]
The [current definition of the RPerp metric](http://rmjarvis.github.io/TreeCorr/html/metric.html#rperp) (as of TreeCorr version 3.3) is as follows:

Rperp^2 = d_3d^2 - Rpar^2

where d_3d is the regular 3d Euclidean distance between two points, and Rpar is defined as |r2 - r1|, the difference in the distances to the two objects.

It turns out this is slightly different from the definition proposed by [Fisher et al, 1994](http://articles.adsabs.harvard.edu/cgi-bin/nph-iarticle_query?1994MNRAS.267..927F&amp;data_type=PDF_HIGH&amp;whole_paper=YES&amp;type=PRINTER&amp;filetype=.pdf), which seems to be the standard reference to this.

Fisher et al define Rperp the same in terms of Rpar, but the difference is that they define Rpar as

s = p2 - p1
L = (p1 + p2)/2
Rpar = |s . L| / |L|

where these are all vectors and the . in the last line is a vector dot product.

I'd like to change the Rperp metric to use this definition instead of the current one for several reasons:
1. It seems to be the standard definition, so probably better scientifically for TreeCorr to conform to that.
2. It turns out that the Fisher definition is easier to compute numerically.  There are fewer sqrts required in that definition.  Mostly because the whole calculation simplifies to Rperp = |s x L| / |L| where the x is a vector cross product, which is easy to compute.
3. The Fisher definition also seems to be more stable in some edge cases, which had been a little tricky to handle properly in TreeCorr.  So for some other work I've been doing to refactor some of the code, I found that parts of the code could become much simpler if I switched to the Fisher definition.

However, this would be an API change.  So I'm pinging some known users of the Rperp metric to ask if anyone would mind if this change happens in the next TreeCorr version.  
* Is it ok to have a different definition of the RPerp metric between version 3.3 and 3.4?
* Is this a disruptive enough change that I should bump to 4.0? (Typically API changes are frowned upon for minor version numbers, but allowed for major version numbers.)
* Do you still want access to the old definition?
* Should I add a metric called e.g. OldRPerp that keep the old definition?
* Would you prefer making this a new metric name and keeping the old one around?  E.g. FisherRPerp vs. the old RPerp?

Thanks.

@erozo @tmcclintock @ebaxter @wagoner47 @elvinpoole @gvalogia @matroxel @jablazek @beckermr

**Comment by beckermr** [comment]
Bumping to 4 seems good. Def leave the old one as an option but I’d put the fisher one as Rperp

**Comment by rmjarvis** [comment]
OK.  From the volume of response, I take it no one really cares too much.  But I'll still do this in an backwards-compatible way for 3.x and only break things at 4.0.

For 3.4+, Rperp will still be the same, but there will be two new ones: FisherRperp is the new one that uses the Fisher et al definition.  And OldRperp is another name for the current one.

For 4.0+, OldRperp and FisherRperp will continue to have the same definitions.  But Rperp will switch over to being an alias of FisherRperp.

This way you can investigate whether the difference has any impact on your science.

**Comment by rmjarvis** [comment]
Done in PR #77.  Will be included in v3.4.
