### ISSUE TITLE
OpenMP with clang

### ISSUE THREAD

**Issue by danpryer** [rmjarvis/TreeCorr#75]
Hi Mike,
I've been successfully using treecorr recently (thanks!), but its only running on one core on my mac and im trying to get it to use OpenMP so i can use e.g. 3 cores to speed things up as some of my NN 3D correlations are taking a bit of time. When installing, i believe the block of output text of interest is:

____________________________________________________________
compiler version information: 
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
Using compiler cc, which is clang
Unable to compile file with #include "ffi.h"
Failed command is:  cc -O3 -ffast-math -c /var/folders/cg/65rg0n450372q2mdlcsq24mc0000gn/T/tmpjN9kL_.c -o /var/folders/cg/65rg0n450372q2mdlcsq24mc0000gn/T/tmpJRFq9r.os
Found ffi/ffi.h
Successfully linked with -lffi
___________________________________________________________

When I create a treecorr config file with 'num_threads: 3' I get an error message along the lines "unable to use multiple cores as openMP is not enabled". I know my machine has openmp as i can get it to work with my c++ programs. I'm pretty sure those programs are using my brew libomp install (https://formulae.brew.sh/formula/libomp ).

Is there some way i can get my treecorr to use this libomp? I played around a bit with the setup.py to try and force it to use openmp but that didnt work.  As far as i can tell my command line tools are up to date.
Any help appreciated!
Cheers
Dan

**Comment by rmjarvis** [comment]
Which version of TreeCorr are you using?  I think I fixed this already on 3.3.10.  If you are using a version before this, you should upgrade and let me know if it's still not working.

**Comment by danpryer** [comment]
Hi, thanks for the fast reply! Im using 3.3.11 according to my pip install. 
Should i maybe try a manual install instead?

**Comment by rmjarvis** [comment]
Well, try that.  But if that doesn't work, I might ask you to add some print statements to the setup.py file to try to figure out why it's not working properly on your system.

**Comment by danpryer** [comment]
Ok tried it and it didnt seem to work.

So im in the setup.py and i have put in some test prints.
I have found that it triggers the if statement on line 96:
    if 'clang' in line:

it then triggers the      else: return 'clang'      bit. So im not sure how its interacting with the try_cc cpp code.. i tried to put some print statements in that (printf and std::cout) but nothing returned when i ran setup.py

**Comment by rmjarvis** [comment]
Try checking out the branch `pryer`.  I added some diagnostic print statements that might help figure this out.

**Comment by danpryer** [comment]
Thanks! output from an install is:


Using setuptools version 40.8.0
Python version =  2.7.15 (default, Feb 12 2019, 11:00:12) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
running install
running bdist_egg
running egg_info
writing requirements to TreeCorr.egg-info/requires.txt
writing TreeCorr.egg-info/PKG-INFO
writing top-level names to TreeCorr.egg-info/top_level.txt
writing dependency_links to TreeCorr.egg-info/dependency_links.txt
reading manifest file 'TreeCorr.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.so' under directory 'treecorr'
writing manifest file 'TreeCorr.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.14-x86_64/egg
running install_lib
running build_py
running build_ext
compiler version information: 
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
Start try_cc:  clang clang w/ OpenMP
wrote file  /var/folders/cg/65rg0n450372q2mdlcsq24mc0000gn/T/tmpaEFXnb.cpp
object file will be  /var/folders/cg/65rg0n450372q2mdlcsq24mc0000gn/T/tmppIYc2a.os
Trying to compile with command:
 ['clang', '-fopenmp', '-O3', '-ffast-math', '-c', '/var/folders/cg/65rg0n450372q2mdlcsq24mc0000gn/T/tmpaEFXnb.cpp', '-o', '/var/folders/cg/65rg0n450372q2mdlcsq24mc0000gn/T/tmppIYc2a.os']
Output is
 ["clang: error: unsupported option '-fopenmp'\n"]
Return code is  1
Compilation failed.  Returning false
Using compiler clang
Unable to compile file with #include "ffi.h"
Failed command is:  clang -O3 -ffast-math -c /var/folders/cg/65rg0n450372q2mdlcsq24mc0000gn/T/tmp65bQ8v.c -o /var/folders/cg/65rg0n450372q2mdlcsq24mc0000gn/T/tmpVEcS16.os
Found ffi/ffi.h
Successfully linked with -lffi
creating build/bdist.macosx-10.14-x86_64/egg
creating build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/catalog.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/field.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/ngcorrelation.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/_treecorr.so -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/binnedcorr3.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/ggcorrelation.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/config.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/binnedcorr2.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/kkkcorrelation.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/_version.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/nnncorrelation.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/util.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
creating build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/PairCell.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/Position_C.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/Metric.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/Field.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/Metric_C.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/Cell.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/BinnedCorr3_C.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/BinnedCorr2.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/ProjectHelper.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/BinnedCorr2_C.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/Field_C.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/Process3.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/BinnedCorr3.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/Process2.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/Bounds.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/dbg.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/Position.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/include/Split.h -> build/bdist.macosx-10.14-x86_64/egg/treecorr/include
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/nncorrelation.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/__init__.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/celestial.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/kgcorrelation.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/gggcorrelation.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/nkcorrelation.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/corr3.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/kkcorrelation.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
copying build/lib.macosx-10.14-x86_64-2.7/treecorr/corr2.py -> build/bdist.macosx-10.14-x86_64/egg/treecorr
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/catalog.py to catalog.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/field.py to field.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/ngcorrelation.py to ngcorrelation.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/binnedcorr3.py to binnedcorr3.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/ggcorrelation.py to ggcorrelation.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/config.py to config.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/binnedcorr2.py to binnedcorr2.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/kkkcorrelation.py to kkkcorrelation.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/_version.py to _version.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/nnncorrelation.py to nnncorrelation.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/util.py to util.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/nncorrelation.py to nncorrelation.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/celestial.py to celestial.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/kgcorrelation.py to kgcorrelation.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/gggcorrelation.py to gggcorrelation.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/nkcorrelation.py to nkcorrelation.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/corr3.py to corr3.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/kkcorrelation.py to kkcorrelation.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/corr2.py to corr2.pyc
creating stub loader for treecorr/_treecorr.so
byte-compiling build/bdist.macosx-10.14-x86_64/egg/treecorr/_treecorr.py to _treecorr.pyc
creating build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
installing scripts to build/bdist.macosx-10.14-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.macosx-10.14-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/corr2 -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/corr3 -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.macosx-10.14-x86_64/egg/EGG-INFO/scripts/corr2 to 755
changing mode of build/bdist.macosx-10.14-x86_64/egg/EGG-INFO/scripts/corr3 to 755
copying TreeCorr.egg-info/PKG-INFO -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying TreeCorr.egg-info/SOURCES.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying TreeCorr.egg-info/dependency_links.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying TreeCorr.egg-info/requires.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying TreeCorr.egg-info/top_level.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.14-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
treecorr.__init__: module references __file__
creating 'dist/TreeCorr-3.3.11-py2.7-macosx-10.14-x86_64.egg' and adding 'build/bdist.macosx-10.14-x86_64/egg' to it
removing 'build/bdist.macosx-10.14-x86_64/egg' (and everything under it)
Processing TreeCorr-3.3.11-py2.7-macosx-10.14-x86_64.egg
removing '/usr/local/lib/python2.7/site-packages/TreeCorr-3.3.11-py2.7-macosx-10.14-x86_64.egg' (and everything under it)
creating /usr/local/lib/python2.7/site-packages/TreeCorr-3.3.11-py2.7-macosx-10.14-x86_64.egg
Extracting TreeCorr-3.3.11-py2.7-macosx-10.14-x86_64.egg to /usr/local/lib/python2.7/site-packages
TreeCorr 3.3.11 is already the active version in easy-install.pth
Installing corr2 script to /usr/local/bin
Installing corr3 script to /usr/local/bin

Installed /usr/local/lib/python2.7/site-packages/TreeCorr-3.3.11-py2.7-macosx-10.14-x86_64.egg
Processing dependencies for TreeCorr==3.3.11
Searching for pandas==0.24.1
Best match: pandas 0.24.1
Adding pandas 0.24.1 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Searching for PyYAML==3.13
Best match: PyYAML 3.13
Adding PyYAML 3.13 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Searching for fitsio==0.9.12
Best match: fitsio 0.9.12
Adding fitsio 0.9.12 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Searching for cffi==1.11.5
Best match: cffi 1.11.5
Adding cffi 1.11.5 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Searching for future==0.17.1
Best match: future 0.17.1
Adding future 0.17.1 to easy-install.pth file
Installing pasteurize script to /usr/local/bin
Installing futurize script to /usr/local/bin

Using /usr/local/lib/python2.7/site-packages
Searching for numpy==1.16.1
Best match: numpy 1.16.1
Adding numpy 1.16.1 to easy-install.pth file
Installing f2py2 script to /usr/local/bin
Installing f2py script to /usr/local/bin
Installing f2py2.7 script to /usr/local/bin

Using /usr/local/lib/python2.7/site-packages
Searching for pytz==2018.5
Best match: pytz 2018.5
Adding pytz 2018.5 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Searching for python-dateutil==2.7.3
Best match: python-dateutil 2.7.3
Adding python-dateutil 2.7.3 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Searching for pycparser==2.19
Best match: pycparser 2.19
Adding pycparser 2.19 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Finished processing dependencies for TreeCorr==3.3.11

**Comment by rmjarvis** [comment]
Well, this tells me that your clang doesn't support the -fopenmp flag.:
```
["clang: error: unsupported option '-fopenmp'\n"]
```
You said you've had success with OpenMP yourself.  Do you use some other flag for that?  

Or maybe you have multiple clang versions on your system, and the one that you use on the command line isn't the same one that python is finding?

One thing you could check is whether this command works:
```
clang -c src/Field.cpp -Iinclude -fopenmp
```
Also maybe check if `which clang` returns the one in `/Library/Developer/CommandLineTools/usr/bin`.

**Comment by danpryer** [comment]
So i had some problems with open mp before.. i had read that it was included with clan but when i tried to use it with cpp programs it just didnt work / seem like it was there which was odd as i had made sure my mac was all up to date with things. Had to use brew to install libomp and do some library linking etc to get the -fopenmp to work.

when i do: clang -c src/Field.cpp -Iinclude -fopenmp
i get: clang: error: unsupported option '-fopenmp'

and then when i do: which clang
i get: /usr/bin/clang

So i guess i have multiple versions of clang, and my command line is pointing to a "wrong / old" version?

**Comment by rmjarvis** [comment]
Right.  Real clang has supported OpenMP for years now.  But Apple has been slow to incorporate it into XCode.  I still have an older OS, so it doesn't work for me natively, but I was thinking from your post that maybe the newest versions had it finally.  Apparently not.

I use Anaconda, which has its own clang installation, and that one works correctly on my system.  But the system python (which uses the system compiler) doesn't.  So if you're keen to get OpenMP going with python, one possibility would be to install Anaconda python.
