### ISSUE TITLE
Issue with reading Catalogue by TreeCorr

### ISSUE THREAD

**Issue by elahehhayati** [rmjarvis/TreeCorr#78]
I have a catalog that I can read it with fitsio but I keep getting this error when I want to read it by TreeCorr : 'utf-8' codec can't decode byte 0xf5 in position 4933: invalid start byte
Can you please let me know how can I fix this error? Thanks

**Comment by rmjarvis** [comment]
It's hard to say without more information than this.  If you want to post the file and tell me exactly how you're trying to read it with TreeCorr, I can take a look.

**Comment by rmjarvis** [comment]
Closing due to lack of response.
