### ISSUE TITLE
units naming

### ISSUE THREAD

**Issue by jecampagne** [rmjarvis/TreeCorr#87]
Hello,
When declaring a Catalog one uses some naming convention for the units: 
ex. Catalog(ra=cat['RA'], dec=cat['DEC'], ra_units='deg', dec_units='deg')
Now when computing eg. NNCorrelation, one should use a sep_units as
NNCorrelation(min_sep=0.01, max_sep=10, bin_size=0.2, sep_units='degrees')

Could it be possible to unify the the unit naming: ie. 'deg' or 'degrees' ? or does the code already made some internal conversion to allow the user to use both deg or degrees in the code?

Thanks
JE

**Comment by rmjarvis** [comment]
They are equivalent.  Use whichever one you want in both places.
