### ISSUE TITLE
Feature Request: Multiplicative Shear Calibration 

### ISSUE THREAD

**Issue by pranavtifr** [rmjarvis/TreeCorr#89]
It would be nice if the code can perform, Multiplicative Shear Calibration for the Galaxy Lensing Data, similar to the one given in this paper. (https://arxiv.org/abs/1603.07722)

If this can already be done by the code. Can someone tell me how ??

**Comment by rmjarvis** [comment]
I don't know what you're proposing, but normally the shear calibration is done on 1-points statistics, not 2-point.  Those are trivial to calculate, and don't need a tree to speed anything up.  

Also they need an image simulation to do it the way Hildebrandt et al does the calibration.  That's most definitely not in scope for TreeCorr.  So unless you can clarify what exactly you expect TreeCorr to do for you, I don't think this is the code you're looking for.

**Comment by pranavtifr** [comment]
No. I mean use the m values given along with the dataset, to correct for it. Like eqn 19 and 20 in this paper (https://arxiv.org/abs/1608.07581). 
it involves scaling all the data points by 1/1+m and the weights by 1+m. I currently loop over the data in advance before computing the correlation functions. But it would be nice if the code could perform faster with the cpp backend.

**Comment by rmjarvis** [comment]
I see.  Yes, TreeCorr can compute the things you need for that.

The first term in eqn 19 is obtained by the KGCorrelation class where the first catalog has k=y, and the second has g1,g2 = e1,e2 and w=w.

The correction factor 1+K is obtained by the NKCorrelation class where the first catalog is the same as in the first case, and the second as k=m and w=w.  

You can even use the same two catalogs for both runs by setting g1, g2, and k in the second catalog.  TreeCorr will just use the bits it needs in each run.

**Comment by pranavtifr** [comment]
Ah. Now I understand how the NKCorrelation class works. Thanks a lot.
